version: '3.4'

services:
  headlessrenderer:
    image: lauramazzuca/headless-renderer:latest
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  webrtcstreamer:
    image: lauramazzuca/webrtc-streamer:latest
    network_mode: host
    
